// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
int add(double a, double b);
extern "C" SEXP _roxydocs_add(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(add(cpp11::as_cpp<cpp11::decay_t<double>>(a), cpp11::as_cpp<cpp11::decay_t<double>>(b)));
  END_CPP11
}
// code.cpp
int times(double a, double b);
extern "C" SEXP _roxydocs_times(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(times(cpp11::as_cpp<cpp11::decay_t<double>>(a), cpp11::as_cpp<cpp11::decay_t<double>>(b)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_roxydocs_add",   (DL_FUNC) &_roxydocs_add,   2},
    {"_roxydocs_times", (DL_FUNC) &_roxydocs_times, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_roxydocs(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
